//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АбонентыEntities : DbContext
    {
        public static АбонентыEntities _context;
        public АбонентыEntities()
            : base("name=АбонентыEntities")
        {
        }
    
        public static АбонентыEntities GetContext()
        {
            if (_context == null)
                _context = new АбонентыEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Абоненты> Абоненты { get; set; }
        public virtual DbSet<Разговоры> Разговоры { get; set; }
        public virtual DbSet<Тарифы> Тарифы { get; set; }
        public virtual DbSet<Телефоны_Абонентов> Телефоны_Абонентов { get; set; }
    }
}
