//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public int id_Разговоры { get; set; }
        public string Город { get; set; }
        public System.DateTime Дата_разговора { get; set; }
        public Nullable<System.TimeSpan> Продолжительность { get; set; }
        public string Статус_оплаты { get; set; }
        public Nullable<int> id_Телефона_Абонента { get; set; }
        public Nullable<int> id_Тарифа { get; set; }
    
        public virtual Тарифы Тарифы { get; set; }
        public virtual Телефоны_Абонентов Телефоны_Абонентов { get; set; }
    }
}
