//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефоны_Абонентов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефоны_Абонентов()
        {
            this.Разговоры = new HashSet<Разговоры>();
        }
    
        public int id_Телефона_Абонента { get; set; }
        public int Номер_Договора { get; set; }
        public System.DateTime Дата_Установки { get; set; }
        public Nullable<int> id_Абонента { get; set; }
        public string Номер { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Разговоры> Разговоры { get; set; }
    }
}
